[package]
name = "nisti-work"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }
dotenvy = "0.15"

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-dialog = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.31.0", features = ["bundled"] }
rusqlite_migration = "1.2.0"
chrono = { version = "0.4.38", features = ["serde"] }
lazy_static = "1.5.0"
uuid = { version = "1.10.0", features = ["v4"] }
tauri-plugin-opener = "2"
reqwest = { version = "0.12", features = ["json"] }
rand = "0.8"
sha2 = "0.10"
base64 = "0.22"
url = "2.5"
tokio = { version = "1", features = ["full"] }
open = "5.4.2"

[target.'cfg(target_os = "windows")'.dependencies]
keyring = { version = "3.2", features = ["windows-native"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
keyring = "3.2"
